import Head from "next/head";
import styles from "@/styles/Home.module.css";
import TimelineCards from "./components/timelineCards";
import { getCommits } from "./api/github-api";

export default function Home() {
  let projectname = "github-timeline-api";
  let username = "joxedanielc";
  const { response, error, isLoading } = getCommits(username, projectname);

  return (
    <>
      <Head>
        <title>{projectname}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="container text-center">
          <div className="row justify-content-md-center mt-4 mb-2">
            <div className="col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <h1 className="text-primary">{projectname}</h1>
            </div>
          </div>
          {response !== undefined ? (
            <TimelineCards timelineData={response} />
          ) : (
            <div className="row">
              <div className="col-lg-12 d-flex justify-content-center">
                {isLoading ? (
                  <>
                    <div className="spinner-border" role="status">
                      <span className="visually-hidden">Loading...</span>
                    </div>
                  </>
                ) : (
                  <div className="alert alert-info" role="alert">
                    {"The was a problem trying to retrieved the commits."}
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </main>
    </>
  );
}
